# Generated by Django 3.1.1 on 2020-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='identity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
