# Generated by Django 3.1.1 on 2020-10-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_auto_20201001_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='body',
            field=models.TextField(default='hero'),
        ),
    ]
