# Generated by Django 3.1 on 2020-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(default='Hero', max_length=50),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(default='Money', max_length=50),
        ),
    ]
